### ISSUE TITLE
Auto-merge prs with Mergify

### ISSUE THREAD

**Issue by markus1189** [moia-dev/scynamo#54]
Hey :wave: just a as a nudge, given that this is an open source project you could try out Mergify to automatically handle the steward prs :)

Here is the relevant section in Scala Steward:
https://github.com/fthomas/scala-steward/blob/master/docs/faq.md#how-can-scala-stewards-prs-be-merged-automatically

Greetings to the whole team :wave:

**Comment by CristinaHG** [comment]
Thanks Markus! 😺 Just created a task for any of us to take a look to it. I miss you a lot!!

**Comment by markus1189** [comment]
Hey @CristinaHG nice to hear from you :smile:

**Comment by saeltz** [comment]
Done in https://github.com/moia-dev/scynamo/pull/134.
